### ISSUE TITLE
Usage example of `this.$pluralize`

### ISSUE THREAD

**Issue by lackovic** [SimpleNexus/vue-pluralize#6]
Can you make a usage example of `this.$pluralize`?
Maybe add it to the README too?

I am going to try and attempt to make one:

```js
const usersCountLabel = this.$pluralize('user', 10);
// usersCountLabel contains "users"
```

**Comment by catskull** [comment]
@lackovic submit a PR and I'd love to merge it!

**Comment by lackovic** [comment]
> @lackovic submit a PR and I'd love to merge it!

Here you are https://github.com/SimpleNexus/vue-pluralize/pull/7

**Comment by catskull** [comment]
Merged! Thanks
